name: NIF Release

on:
  workflow_call:
    inputs:
      project-name:
        type: string
        required: true
        description: "Name of the NIF project (e.g., 'my_nif')"
      project-dir:
        type: string
        required: true
        description: "Directory containing the NIF project (e.g., 'native/my_nif')"
      nif-versions:
        type: string
        default: '["2.15"]'
        description: "NIF versions to build for"

jobs:
  build:
    name: ${{ matrix.job.os }} ${{ matrix.job.target }}, ${{ matrix.nif }}, ${{ matrix.job.variant || 'default' }}
    runs-on: ${{ matrix.job.os }}
    timeout-minutes: 60

    permissions:
      contents: write
      id-token: write
      attestations: write

    strategy:
      fail-fast: false
      matrix:
        nif: ${{ fromJSON(inputs.nif-versions) }}
        job:
          - { target: aarch64-apple-darwin,         os: macos-13 }
          - { target: aarch64-unknown-linux-gnu,    os: ubuntu-22.04, use-cross: true }
          - { target: aarch64-unknown-linux-musl,   os: ubuntu-24.04, use-cross: true }
          - { target: arm-unknown-linux-gnueabihf,  os: ubuntu-24.04, use-cross: true }
          - { target: riscv64gc-unknown-linux-gnu,  os: ubuntu-24.04, use-cross: true }
          - { target: x86_64-apple-darwin,          os: macos-13 }
          - { target: x86_64-pc-windows-gnu,        os: windows-2022,                  rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-pc-windows-gnu,        os: windows-2022,                  variant: "legacy_cpu" }
          - { target: x86_64-pc-windows-msvc,       os: windows-2022,                  rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-pc-windows-msvc,       os: windows-2022,                  variant: "legacy_cpu" }
          - { target: x86_64-unknown-freebsd,       os: ubuntu-22.04, use-cross: true, rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-unknown-freebsd,       os: ubuntu-22.04, use-cross: true, variant: "legacy_cpu" }
          - { target: x86_64-unknown-linux-gnu,     os: ubuntu-24.04,                  rustflags: "-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma" }
          - { target: x86_64-unknown-linux-gnu,     os: ubuntu-24.04,                  variant: "legacy_cpu" }
          - { target: x86_64-unknown-linux-musl,    os: ubuntu-24.04, use-cross: true }
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Extract crate information
        shell: bash
        run: |
          # Get the project version from mix.exs
          echo "PROJECT_VERSION=$(sed -n 's/^  @version "\(.*\)"/\1/p' mix.exs | head -n1)" >> "$GITHUB_ENV"

      - name: Maybe add Rust flags for compilation
        shell: bash
        run: |
          echo "RUSTFLAGS=${{ matrix.job.rustflags }}" >> "$GITHUB_ENV"
        if: ${{ matrix.job.rustflags }}

      - name: Add target
        shell: bash
        run: |
          rustup target add ${{ matrix.job.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v0-precomp
          shared-key: ${{ matrix.job.target }}-${{ matrix.nif }}-${{ matrix.job.os }}
          workspaces: |
            ${{ inputs.project-dir }}

      - name: Build the project
        id: build-crate
        uses: philss/rustler-precompiled-action@v1.1.4
        with:
          project-name: ${{ inputs.project-name }}
          project-version: ${{ env.PROJECT_VERSION }}
          target: ${{ matrix.job.target }}
          nif-version: ${{ matrix.nif }}
          use-cross: ${{ matrix.job.use-cross }}
          cross-version: 'from-source'
          project-dir: ${{ inputs.project-dir }}
          variant: ${{ matrix.job.variant }}

      - name: Artifact attestation
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ steps.build-crate.outputs.file-path }}

      - name: Artifact upload
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.build-crate.outputs.file-name }}
          path: ${{ steps.build-crate.outputs.file-path }}

      - name: Publish archives and packages
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.build-crate.outputs.file-path }}
        if: startsWith(github.ref, 'refs/tags/')
